version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    volumes:
    - app-data:/app
    expose:
      - ${PORT}
    ports:
      - '${PORT}:${PORT}'
    restart: always
    environment:
      NODE_ENV: production
    command: npm run start
volumes:
  app-data: