version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - app-data:/app
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    expose:
      - ${PORT}
    ports:
      - '${PORT}:${PORT}'
    command: npm run start
volumes:
  app-data:
# version: '3.8'

# services:
#   api_java_app:
#     image: api_java_app:latest
#   app:
#     build:
#       context: .
#       dockerfile: ./docker/Dockerfile.dev
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     environment:
#       - NODE_ENV=development
#       - AUTH_SERVICE=api_java_app:latest
#     expose:
#       - ${PORT}
#     ports:
#       - '${PORT}:${PORT}'
#     command: npm run dev
# networks:
#   my-network:
#     driver: bridge