FROM node:20-alpine3.16
# Create a new directory for the application
WORKDIR /usr/src/app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application code into the container
COPY . .


# # Set the application's port number
# ENV PORT 3000

# # Expose the port number to the outside world
# EXPOSE 3000
# # Start the application with nodemon and the ESM module loader
CMD ["nodemon", "--experimental-specifier-resolution=node", "--watch", ".", "--ext", "js,json", "src/index.js"]